### ISSUE TITLE
Bad Style in fastpy.constrain_solver.py

### ISSUE THREAD

**Issue by nimaje** [tartavull/fastpy#4]
you use a class as namespace where the orginal code (https://github.com/sdiehl/numpile) doesn't use a class ([here](https://github.com/sdiehl/numpile/blob/master/numpile.py#L319)) (because the orginal code only uses one file a class as namespace could be helpful)

btw: why did you rename the decorator from `autojit` to fast? and why didn't you fork the orginal project?

**Comment by tartavull** [comment]
Hi @nimaje

Thanks for taking the time to right this issue.
The problem was that the constraint solver apply function was colliding with Python's built-in function apply.
The main goal of the project is for me to understand Stephen's great tutorial, that's why I've been dividing into modules and starting writting some docstrings. 

The reason for renaming autojit to fast is because, in my opinion, it express the purpose of what you want when using the decorator. I don't care if the function is compile just in time, I only care about it running fast.

The reason for not forking the original project was that the original code serves as a tutorial where having a single file and nothing else is a great approach. This repo have all this files for deployment and testing that would be distracting as a tutorial. In other words, I thought the point of forking was to later do a PR, but I don't think this project would improve Stephen's numpile but rather the opposite.

**Comment by nimaje** [comment]
you could ignore the name collision because it's only a small module and you don't need the build-in apply (https://docs.python.org/2/library/functions.html#apply).
you should use the `requirements.txt` from the orginal project.

**Comment by tartavull** [comment]
This [https://github.com/tartavull/fastpy/commit/eec1dee5a85d78bd583cedd133b52b714a313e34](commit) adds the requirements, thanks for the advise.
I'll do another commit for the apply
